name: D

on: push

permissions:
  contents: read

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dlang-community/setup-dlang@4c99aa991ce7d19dd3064de0a4f2f6b2f152e2d7

    - name: 'Setup'
      run: |
        sudo apt-get install xorg-dev

    - name: 'Build BeanDS'
      run: |
        # Build the project, with its main file included, without unittests
        dub build --compiler=$DC
